/**
 * Mock data untuk development saat backend belum siap.
 * Import di komponen dengan: import { mockProducts } from "@/lib/mockData"
 */

import type {
  Product,
  Supplier,
  StaffMember,
  TransactionHistory,
  AuditLog,
  StorageZone,
} from "@/types";

export const mockProducts: Product[] = [
  {
    id: "b5c6d7e8-f9a0-1b2c-3d4e-5f6a7b8c9d0e",
    sku_code: "SKU-C-001",
    name: "Semen Tiga Roda 50kg",
    category: "Cement & Sand",
    supplier: "PT Semen Indonesia",
    buy_price: "60000.00",
    sell_price: "65000.00",
    current_stock: 450,
    defective_stock: 0,
    min_stock: 100,
    rack_location: "R-A1-01",
  },
  {
    id: "c6d7e8f9-a0b1-2c3d-4e5f-6a7b8c9d0e1f",
    sku_code: "SKU-S-10M",
    name: "Besi Beton Polos 10mm",
    category: "Steel",
    supplier: "Krakatau Steel Dist.",
    buy_price: "95000.00",
    sell_price: "105000.00",
    current_stock: 1200,
    defective_stock: 2,
    min_stock: 500,
    rack_location: "R-B2-04",
  },
  {
    id: "d7e8f9a0-b1c2-3d4e-5f6a-7b8c9d0e1f2a",
    sku_code: "SKU-N-9SC",
    name: "Paku Kayu 5cm",
    category: "Hardware",
    supplier: "CV Logam Jaya",
    buy_price: "18000.00",
    sell_price: "22000.00",
    current_stock: 45,
    defective_stock: 0,
    min_stock: 200,
    rack_location: "R-C1-12",
  },
  {
    id: "e8f9a0b1-c2d3-4e5f-6a7b-8c9d0e1f2a3b",
    sku_code: "SKU-P-W25",
    name: "Cat Tembok Putih 25kg",
    category: "Paints",
    supplier: "Avian Brands",
    buy_price: "210000.00",
    sell_price: "245000.00",
    current_stock: 85,
    defective_stock: 0,
    min_stock: 20,
    rack_location: "R-D3-02",
  },
  {
    id: "f9a0b1c2-d3e4-5f6a-7b8c-9d0e1f2a3b4c",
    sku_code: "SKU-W-T12",
    name: "Triplek 12mm 122×244",
    category: "Timber",
    supplier: "Jati Indah Timber",
    buy_price: "145000.00",
    sell_price: "165000.00",
    current_stock: 12,
    defective_stock: 1,
    min_stock: 50,
    rack_location: "R-A2-08",
  },
  {
    id: "a0b1c2d3-e4f5-6a7b-8c9d-0e1f2a3b4c5d",
    sku_code: "SKU-P-AW12",
    name: "Pipa Wavin AW 1/2\"",
    category: "Pipes & Fittings",
    supplier: "PT Wavin Indonesia",
    buy_price: "28000.00",
    sell_price: "32000.00",
    current_stock: 120,
    defective_stock: 0,
    min_stock: 50,
    rack_location: "R-C3-12",
  },
  {
    id: "b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e",
    sku_code: "SKU-SMN-GR40",
    name: "Semen Gresik 40kg",
    category: "Cement & Sand",
    supplier: "PT Semen Indonesia",
    buy_price: "48000.00",
    sell_price: "52000.00",
    current_stock: 310,
    defective_stock: 0,
    min_stock: 100,
    rack_location: "R-A1-02",
  },
  {
    id: "c2d3e4f5-a6b7-8c9d-0e1f-2a3b4c5d6e7f",
    sku_code: "SKU-CAT-DLX5",
    name: "Cat Tembok Dulux 5kg",
    category: "Paints",
    supplier: "Dulux Indonesia",
    buy_price: "120000.00",
    sell_price: "145000.00",
    current_stock: 0,
    defective_stock: 0,
    min_stock: 30,
    rack_location: "R-B2-05",
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: "s1",
    supplier_id: "SUP-1024",
    vendor_name: "Semen Indonesia Persero",
    category: "Cement",
    primary_contact: "Budi Santoso",
    phone: "+62 812-3456-7890",
    status: "Active",
    rating: 4.5,
  },
  {
    id: "s2",
    supplier_id: "SUP-1089",
    vendor_name: "Krakatau Steel Tbk",
    category: "Steel",
    primary_contact: "Andi Wijaya",
    phone: "+62 811-2233-4455",
    status: "Active",
    rating: 4.0,
  },
  {
    id: "s3",
    supplier_id: "SUP-1102",
    vendor_name: "Avian Brands",
    category: "Paint",
    primary_contact: "Siti Aminah",
    phone: "+62 856-7788-9900",
    status: "On Hold",
    rating: 3.5,
  },
  {
    id: "s4",
    supplier_id: "SUP-1155",
    vendor_name: "Jati Indah Timber",
    category: "Timber",
    primary_contact: "Rudi Hartono",
    phone: "+62 819-1122-3344",
    status: "Active",
    rating: 4.5,
  },
];

export const mockStaff: StaffMember[] = [
  {
    id: "stf1",
    employee_id: "STF001",
    full_name: "Andi Wijaya",
    role: "OWNER",
    last_active: new Date(Date.now() - 2 * 60000).toISOString(),
    is_active: true,
  },
  {
    id: "stf2",
    employee_id: "STF002",
    full_name: "Siti Aminah",
    role: "CASHIER",
    last_active: new Date(Date.now() - 15 * 60000).toISOString(),
    is_active: true,
  },
  {
    id: "stf3",
    employee_id: "STF003",
    full_name: "Budi Santoso",
    role: "CASHIER",
    last_active: new Date(Date.now() - 60 * 60000).toISOString(),
    is_active: false,
  },
];

export const mockTransactions: TransactionHistory[] = [
  {
    id: "t1",
    invoice_no: "#TRX-99824",
    date: "2023-10-24T14:32:00.000Z",
    customer: "PT. Maju Jaya",
    customer_type: "VIP",
    method: "Transfer",
    total_amount: "12500000",
    status: "Success",
    cashier: "Cashier 01",
  },
  {
    id: "t2",
    invoice_no: "#TRX-99823",
    date: "2023-10-24T13:15:00.000Z",
    customer: "Bpk. Budi Santoso",
    customer_type: "Regular",
    method: "Credit",
    total_amount: "4200000",
    status: "Pending",
    cashier: "Cashier 02",
  },
  {
    id: "t3",
    invoice_no: "#TRX-99820",
    date: "2023-10-24T11:45:00.000Z",
    customer: "Toko Bangunan Anugrah",
    customer_type: "Regular",
    method: "Cash",
    total_amount: "850000",
    status: "Cancelled",
    cashier: "Cashier 01",
  },
  {
    id: "t4",
    invoice_no: "#TRX-99819",
    date: "2023-10-24T09:20:00.000Z",
    customer: "Walk-in Customer",
    customer_type: "Regular",
    method: "Cash",
    total_amount: "120000",
    status: "Success",
    cashier: "Cashier 02",
  },
];

export const mockAuditLogs: any[] = [
  {
    id: "log1",
    user: "Owner",
    action: "VIEW_TRANSACTION",
    table_name: "transactions",
    record_id: "TRX-99824",
    changes_payload: { old_values: null, new_values: null },
    created_at: new Date().toISOString(),
  },
  {
    id: "log2",
    user: "Cashier 01",
    action: "REPRINT_RECEIPT",
    table_name: "transactions",
    record_id: "TRX-99824",
    changes_payload: { old_values: null, new_values: null },
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    id: "log3",
    user: "Owner",
    action: "CANCEL_TRANSACTION",
    table_name: "transactions",
    record_id: "TRX-99820",
    changes_payload: {
      old_values: { reason: "Stock mismatch" },
      new_values: null,
    },
    created_at: new Date(Date.now() - 45 * 60000).toISOString(),
  },
];

export const mockStorageZones: StorageZone[] = [
  {
    name: "Zone A: Heavy Materials",
    description: "Cement, Steel Rebars, Bricks",
    capacity_percentage: 92,
    status: "High Utilization",
    rack_range: "Rack A1-A5",
    zone_type: "Floor Storage",
  },
  {
    name: "Zone B: Finishing",
    description: "Paint, Tiles, Ceramics",
    capacity_percentage: 70,
    status: "Normal",
    rack_range: "Rack B1-B8",
    zone_type: "Shelving",
  },
  {
    name: "Zone C: Hardware",
    description: "Nails, Screws, Hand Tools",
    capacity_percentage: 45,
    status: "Normal",
    rack_range: "Rack C1-C6",
    zone_type: "Cabinet",
  },
  {
    name: "Zone D: Bulk Outdoors",
    description: "Sand, Gravel, Raw Timber",
    capacity_percentage: 60,
    status: "Normal",
    rack_range: "Yard D1-D4",
    zone_type: "Outdoor",
  },
];

export const mockSalesData = [
  { day: "Sen", value: 18 },
  { day: "Sel", value: 22 },
  { day: "Rab", value: 15 },
  { day: "Kam", value: 25 },
  { day: "Jum", value: 20 },
  { day: "Sab", value: 28 },
  { day: "Min", value: 24 },
];

export const mockRevenueData = [
  { month: "Jan", value: 65 },
  { month: "Feb", value: 72 },
  { month: "Mar", value: 68 },
  { month: "Apr", value: 80 },
  { month: "Mei", value: 58 },
  { month: "Jun", value: 95 },
];
