version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: rukun_jaya_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    restart: unless-stopped
